LANGUAGES: tuple[str, ...] = ("English", "Hindi", "Bengali")

LANGUAGE_NAMES = {
    "English": "English",
    "Hindi": "हिन्दी",
    "Bengali": "বাংলা",
}

STYLE_KEYS: tuple[str, ...] = (
    "simple",
    "step_by_step",
    "elderly",
    "farmer",
    "student",
)

TRANSLATIONS: dict[str, dict[str, str]] = {
    "English": {
        "page_title": "Document Assistant",
        "choose_language": "Choose your language",
        "choose_language_help": "Select a language to continue.",
        "language": "Language",
        "continue": "Continue",
        "response_settings": "Response settings",
        "selected_language": "Selected language",
        "change_language": "Change language",
        "explanation_style": "Explanation style",
        "explanation_style_help": "Choose the level and style of explanation.",
        "current_session": "Current session",
        "session_counts": "{facts} extracted facts · {messages} messages",
        "no_active_document": "No active document",
        "reset_session": "Reset session",
        "reset_help": "Clear the document, facts, and conversation.",
        "session_privacy": "Files are kept only for this current session.",
        "title": "Understand your document",
        "intro": "Upload a document and ask questions in the language and explanation style that work best for you.",
        "add_document": "1. Add a document",
        "upload_label": "Upload an image, PDF, or audio recording",
        "upload_button": "Choose file",
        "upload_limits": "Accepted: PNG, JPG, JPEG, PDF, WAV, MP3, M4A. File limits depend on the format.",
        "upload_help": "PNG/JPEG up to 10 MB, PDF up to 20 MB, or WAV/MP3/M4A up to 15 MB and 30 seconds.",
        "choose_file": "Choose a clear image, PDF, or short audio recording to begin.",
        "validating": "Validating the file and preparing a preview…",
        "upload_error": "The file could not be processed. Check its format, size, and contents.",
        "ready": "Ready: {filename}",
        "kind_image": "Image",
        "kind_pdf": "PDF",
        "kind_audio": "Audio",
        "image_preview": "Image preview · {source_width}×{source_height} source · {width}×{height} preview",
        "pdf_preview": "{pages} pages · previewing {shown}{suffix}",
        "additional_pages": " · additional pages not shown",
        "page": "Page {number}",
        "seconds": "{value:.1f} seconds",
        "channel": "channel",
        "channels": "channels",
        "pdf_processing": "PDF processing",
        "pdf_counts": "{text_count} text {text_label} · {scan_count} scanned {scan_label}",
        "page_single": "page",
        "page_plural": "pages",
        "embedded_text": "Extracted embedded text",
        "text_truncated": "Extracted text is shortened to keep processing responsive.",
        "no_embedded_text": "No embedded text found. Scanned pages are ready for OCR.",
        "no_scanned_pages": "No scanned pages detected.",
        "scanned_ready": "Scanned pages prepared for OCR",
        "detected_pages": "Detected pages: {pages}",
        "scanned_page": "Scanned page {number}",
        "scanned_truncated": "Additional scanned pages were detected but are not shown here.",
        "session_memory": "Session memory",
        "active_none": "Active document: none",
        "upload_for_memory": "Upload a document to create document-specific memory.",
        "active_document": "Active document",
        "extracted_facts": "Extracted facts",
        "messages": "Messages",
        "no_facts": "No facts have been extracted yet.",
        "fact_page": "page {number}",
        "confidence": "{value:.0%} confidence",
        "evidence": "evidence: {value}",
        "ask_document": "2. Ask about the document",
        "chat_placeholder": "Ask what this document means…",
        "queued_response": "Your question is queued for a {style} response in English.",
        "what_add": "What you can add",
        "guidance": "- Government notices\n- Electricity or property bills\n- Bank and insurance letters\n- Prescriptions and acknowledgements\n- Short voice questions",
        "privacy_warning": "Do not upload passwords, OTPs, or documents you do not have permission to use.",
        "welcome": "Upload an image, PDF, or audio recording, then ask what it means.",
        "document_active": "{filename} is now the active document. What would you like to know?",
        "style_simple": "Simple",
        "style_simple_instruction": "Use short sentences and everyday words.",
        "style_step_by_step": "Step by step",
        "style_step_by_step_instruction": "Explain each required action in order.",
        "style_elderly": "For an elderly family member",
        "style_elderly_instruction": "Speak gently, avoid jargon, and repeat important dates and amounts.",
        "style_farmer": "For a farmer",
        "style_farmer_instruction": "Use practical examples and direct action points.",
        "style_student": "For a student",
        "style_student_instruction": "Explain unfamiliar terms and provide brief context.",
    },
    "Hindi": {
        "page_title": "दस्तावेज़ सहायक",
        "choose_language": "अपनी भाषा चुनें",
        "choose_language_help": "आगे बढ़ने के लिए भाषा चुनें।",
        "language": "भाषा",
        "continue": "आगे बढ़ें",
        "response_settings": "उत्तर की सेटिंग",
        "selected_language": "चुनी हुई भाषा",
        "change_language": "भाषा बदलें",
        "explanation_style": "समझाने का तरीका",
        "explanation_style_help": "समझाने का स्तर और तरीका चुनें।",
        "current_session": "वर्तमान सत्र",
        "session_counts": "{facts} निकाले गए तथ्य · {messages} संदेश",
        "no_active_document": "कोई सक्रिय दस्तावेज़ नहीं",
        "reset_session": "सत्र रीसेट करें",
        "reset_help": "दस्तावेज़, तथ्य और बातचीत साफ़ करें।",
        "session_privacy": "फ़ाइलें केवल इस सत्र के दौरान रखी जाती हैं।",
        "title": "अपने दस्तावेज़ को समझें",
        "intro": "दस्तावेज़ अपलोड करें और अपनी भाषा तथा पसंद के तरीके में प्रश्न पूछें।",
        "add_document": "1. दस्तावेज़ जोड़ें",
        "upload_label": "चित्र, PDF या ऑडियो रिकॉर्डिंग अपलोड करें",
        "upload_button": "फ़ाइल चुनें",
        "upload_limits": "स्वीकृत: PNG, JPG, JPEG, PDF, WAV, MP3, M4A। फ़ाइल की सीमा प्रारूप पर निर्भर है।",
        "upload_help": "PNG/JPEG अधिकतम 10 MB, PDF अधिकतम 20 MB, या WAV/MP3/M4A अधिकतम 15 MB और 30 सेकंड।",
        "choose_file": "शुरू करने के लिए साफ़ चित्र, PDF या छोटी ऑडियो रिकॉर्डिंग चुनें।",
        "validating": "फ़ाइल की जाँच और पूर्वावलोकन तैयार किया जा रहा है…",
        "upload_error": "फ़ाइल संसाधित नहीं हो सकी। उसका प्रारूप, आकार और सामग्री जाँचें।",
        "ready": "तैयार: {filename}",
        "kind_image": "चित्र",
        "kind_pdf": "PDF",
        "kind_audio": "ऑडियो",
        "image_preview": "चित्र पूर्वावलोकन · मूल {source_width}×{source_height} · पूर्वावलोकन {width}×{height}",
        "pdf_preview": "{pages} पृष्ठ · {shown} का पूर्वावलोकन{suffix}",
        "additional_pages": " · बाकी पृष्ठ नहीं दिखाए गए",
        "page": "पृष्ठ {number}",
        "seconds": "{value:.1f} सेकंड",
        "channel": "चैनल",
        "channels": "चैनल",
        "pdf_processing": "PDF संसाधन",
        "pdf_counts": "{text_count} टेक्स्ट {text_label} · {scan_count} स्कैन {scan_label}",
        "page_single": "पृष्ठ",
        "page_plural": "पृष्ठ",
        "embedded_text": "निकाला गया अंतर्निहित टेक्स्ट",
        "text_truncated": "तेज़ संसाधन के लिए निकाला गया टेक्स्ट छोटा किया गया है।",
        "no_embedded_text": "अंतर्निहित टेक्स्ट नहीं मिला। स्कैन किए पृष्ठ OCR के लिए तैयार हैं।",
        "no_scanned_pages": "कोई स्कैन किया पृष्ठ नहीं मिला।",
        "scanned_ready": "OCR के लिए तैयार स्कैन किए पृष्ठ",
        "detected_pages": "मिले हुए पृष्ठ: {pages}",
        "scanned_page": "स्कैन किया पृष्ठ {number}",
        "scanned_truncated": "कुछ और स्कैन किए पृष्ठ मिले, लेकिन यहाँ नहीं दिखाए गए।",
        "session_memory": "सत्र स्मृति",
        "active_none": "सक्रिय दस्तावेज़: कोई नहीं",
        "upload_for_memory": "दस्तावेज़-विशिष्ट स्मृति बनाने के लिए दस्तावेज़ अपलोड करें।",
        "active_document": "सक्रिय दस्तावेज़",
        "extracted_facts": "निकाले गए तथ्य",
        "messages": "संदेश",
        "no_facts": "अभी कोई तथ्य नहीं निकाला गया है।",
        "fact_page": "पृष्ठ {number}",
        "confidence": "{value:.0%} विश्वास",
        "evidence": "साक्ष्य: {value}",
        "ask_document": "2. दस्तावेज़ के बारे में पूछें",
        "chat_placeholder": "पूछें कि इस दस्तावेज़ का क्या अर्थ है…",
        "queued_response": "आपका प्रश्न {style} उत्तर के लिए कतार में है।",
        "what_add": "आप क्या जोड़ सकते हैं",
        "guidance": "- सरकारी सूचनाएँ\n- बिजली या संपत्ति के बिल\n- बैंक और बीमा पत्र\n- पर्चे और पावती\n- छोटे आवाज़ी प्रश्न",
        "privacy_warning": "पासवर्ड, OTP या ऐसे दस्तावेज़ अपलोड न करें जिनके उपयोग की अनुमति आपके पास नहीं है।",
        "welcome": "चित्र, PDF या ऑडियो रिकॉर्डिंग अपलोड करें, फिर उसका अर्थ पूछें।",
        "document_active": "{filename} अब सक्रिय दस्तावेज़ है। आप क्या जानना चाहते हैं?",
        "style_simple": "सरल",
        "style_simple_instruction": "छोटे वाक्य और रोज़मर्रा के शब्द इस्तेमाल करें।",
        "style_step_by_step": "चरण-दर-चरण",
        "style_step_by_step_instruction": "हर ज़रूरी काम सही क्रम में समझाएँ।",
        "style_elderly": "बुज़ुर्ग परिवार सदस्य के लिए",
        "style_elderly_instruction": "नरमी से बोलें, कठिन शब्दों से बचें और महत्वपूर्ण तारीखें व रकम दोहराएँ।",
        "style_farmer": "किसान के लिए",
        "style_farmer_instruction": "व्यावहारिक उदाहरण और सीधे कार्य-बिंदु दें।",
        "style_student": "विद्यार्थी के लिए",
        "style_student_instruction": "अनजान शब्द समझाएँ और संक्षिप्त संदर्भ दें।",
    },
    "Bengali": {
        "page_title": "নথি সহায়ক",
        "choose_language": "আপনার ভাষা নির্বাচন করুন",
        "choose_language_help": "এগিয়ে যেতে একটি ভাষা নির্বাচন করুন।",
        "language": "ভাষা",
        "continue": "এগিয়ে যান",
        "response_settings": "উত্তরের সেটিং",
        "selected_language": "নির্বাচিত ভাষা",
        "change_language": "ভাষা পরিবর্তন করুন",
        "explanation_style": "ব্যাখ্যার ধরন",
        "explanation_style_help": "ব্যাখ্যার স্তর ও ধরন নির্বাচন করুন।",
        "current_session": "বর্তমান সেশন",
        "session_counts": "{facts}টি তথ্য · {messages}টি বার্তা",
        "no_active_document": "কোনো সক্রিয় নথি নেই",
        "reset_session": "সেশন রিসেট করুন",
        "reset_help": "নথি, তথ্য ও কথোপকথন মুছে দিন।",
        "session_privacy": "ফাইলগুলো শুধু এই সেশনের জন্য রাখা হয়।",
        "title": "আপনার নথি বুঝুন",
        "intro": "নথি আপলোড করুন এবং আপনার ভাষা ও পছন্দের ধরনে প্রশ্ন করুন।",
        "add_document": "1. একটি নথি যোগ করুন",
        "upload_label": "ছবি, PDF বা অডিও রেকর্ডিং আপলোড করুন",
        "upload_button": "ফাইল বেছে নিন",
        "upload_limits": "গ্রহণযোগ্য: PNG, JPG, JPEG, PDF, WAV, MP3, M4A। ফাইলের সীমা ধরনের উপর নির্ভর করে।",
        "upload_help": "PNG/JPEG সর্বোচ্চ 10 MB, PDF সর্বোচ্চ 20 MB, অথবা WAV/MP3/M4A সর্বোচ্চ 15 MB ও 30 সেকেন্ড।",
        "choose_file": "শুরু করতে একটি পরিষ্কার ছবি, PDF বা ছোট অডিও রেকর্ডিং নির্বাচন করুন।",
        "validating": "ফাইল যাচাই ও প্রিভিউ প্রস্তুত করা হচ্ছে…",
        "upload_error": "ফাইলটি প্রক্রিয়া করা যায়নি। এর ধরন, আকার ও বিষয়বস্তু পরীক্ষা করুন।",
        "ready": "প্রস্তুত: {filename}",
        "kind_image": "ছবি",
        "kind_pdf": "PDF",
        "kind_audio": "অডিও",
        "image_preview": "ছবির প্রিভিউ · মূল {source_width}×{source_height} · প্রিভিউ {width}×{height}",
        "pdf_preview": "{pages}টি পৃষ্ঠা · {shown}টির প্রিভিউ{suffix}",
        "additional_pages": " · বাকি পৃষ্ঠাগুলো দেখানো হয়নি",
        "page": "পৃষ্ঠা {number}",
        "seconds": "{value:.1f} সেকেন্ড",
        "channel": "চ্যানেল",
        "channels": "চ্যানেল",
        "pdf_processing": "PDF প্রক্রিয়াকরণ",
        "pdf_counts": "{text_count}টি টেক্সট {text_label} · {scan_count}টি স্ক্যান {scan_label}",
        "page_single": "পৃষ্ঠা",
        "page_plural": "পৃষ্ঠা",
        "embedded_text": "নির্গত অন্তর্নিহিত লেখা",
        "text_truncated": "দ্রুত প্রক্রিয়াকরণের জন্য লেখাটি সংক্ষিপ্ত করা হয়েছে।",
        "no_embedded_text": "অন্তর্নিহিত লেখা পাওয়া যায়নি। স্ক্যান করা পৃষ্ঠাগুলো OCR-এর জন্য প্রস্তুত।",
        "no_scanned_pages": "স্ক্যান করা কোনো পৃষ্ঠা পাওয়া যায়নি।",
        "scanned_ready": "OCR-এর জন্য প্রস্তুত স্ক্যান করা পৃষ্ঠা",
        "detected_pages": "পাওয়া পৃষ্ঠা: {pages}",
        "scanned_page": "স্ক্যান করা পৃষ্ঠা {number}",
        "scanned_truncated": "আরও স্ক্যান করা পৃষ্ঠা পাওয়া গেছে, তবে এখানে দেখানো হয়নি।",
        "session_memory": "সেশন স্মৃতি",
        "active_none": "সক্রিয় নথি: নেই",
        "upload_for_memory": "নথি-নির্দিষ্ট স্মৃতি তৈরি করতে একটি নথি আপলোড করুন।",
        "active_document": "সক্রিয় নথি",
        "extracted_facts": "নির্গত তথ্য",
        "messages": "বার্তা",
        "no_facts": "এখনও কোনো তথ্য নির্গত হয়নি।",
        "fact_page": "পৃষ্ঠা {number}",
        "confidence": "{value:.0%} আস্থা",
        "evidence": "প্রমাণ: {value}",
        "ask_document": "2. নথি সম্পর্কে জিজ্ঞাসা করুন",
        "chat_placeholder": "এই নথির অর্থ কী তা জিজ্ঞাসা করুন…",
        "queued_response": "আপনার প্রশ্নটি {style} উত্তরের জন্য সারিতে আছে।",
        "what_add": "আপনি যা যোগ করতে পারেন",
        "guidance": "- সরকারি বিজ্ঞপ্তি\n- বিদ্যুৎ বা সম্পত্তির বিল\n- ব্যাংক ও বিমার চিঠি\n- প্রেসক্রিপশন ও প্রাপ্তিস্বীকার\n- ছোট ভয়েস প্রশ্ন",
        "privacy_warning": "পাসওয়ার্ড, OTP বা ব্যবহারের অনুমতি নেই এমন নথি আপলোড করবেন না।",
        "welcome": "ছবি, PDF বা অডিও রেকর্ডিং আপলোড করুন, তারপর এর অর্থ জিজ্ঞাসা করুন।",
        "document_active": "{filename} এখন সক্রিয় নথি। আপনি কী জানতে চান?",
        "style_simple": "সহজ",
        "style_simple_instruction": "ছোট বাক্য ও দৈনন্দিন শব্দ ব্যবহার করুন।",
        "style_step_by_step": "ধাপে ধাপে",
        "style_step_by_step_instruction": "প্রতিটি প্রয়োজনীয় কাজ সঠিক ক্রমে ব্যাখ্যা করুন।",
        "style_elderly": "বয়স্ক পরিবারের সদস্যের জন্য",
        "style_elderly_instruction": "নরমভাবে বলুন, কঠিন শব্দ এড়ান এবং গুরুত্বপূর্ণ তারিখ ও অর্থের পরিমাণ পুনরাবৃত্তি করুন।",
        "style_farmer": "কৃষকের জন্য",
        "style_farmer_instruction": "ব্যবহারিক উদাহরণ ও সরাসরি করণীয় দিন।",
        "style_student": "শিক্ষার্থীর জন্য",
        "style_student_instruction": "অপরিচিত শব্দ ব্যাখ্যা করুন এবং সংক্ষিপ্ত প্রসঙ্গ দিন।",
    },
}


def language_name(language: str) -> str:
    return LANGUAGE_NAMES[language]


def text(language: str, key: str, **values: object) -> str:
    try:
        template = TRANSLATIONS[language][key]
    except KeyError as error:
        raise ValueError(f"Unknown translation: {language}.{key}") from error
    return template.format(**values)


def style_labels(language: str = "English") -> tuple[str, ...]:
    return tuple(text(language, f"style_{key}") for key in STYLE_KEYS)


def style_label(style_key: str, language: str) -> str:
    if style_key not in STYLE_KEYS:
        raise ValueError(f"Unknown explanation style: {style_key}")
    return text(language, f"style_{style_key}")


def style_instruction(style_key: str, language: str = "English") -> str:
    if style_key not in STYLE_KEYS:
        raise ValueError(f"Unknown explanation style: {style_key}")
    return text(language, f"style_{style_key}_instruction")
